# fly.toml app configuration file generated for expensetracker on 2023-11-12T10:23:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "expensetracker"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200
